### ISSUE TITLE
[질문] 안녕하세요 교수님! 질문있습니다!...

### ISSUE THREAD

**Issue by rhsekdl12** [rhsekdl12/BabsangApp#18]
안녕하세요 교수님 유한대학교 모바일앱전공 201727007 2학년 링크반 홍성휘입니다.
안드로이드 스튜디오를 다루면서 소소한 문제가 있는것 같아서 이렇게 질문드립니다

현재 안드로이드 스튜디오를 하면서 메인 xml에서 화면을 재구성하기 위하여 편집을 하고싶은데,
메인xml에서만 화면구성(레이아웃, 버튼, 텍스트 등의 변경)을 다시 해보아도 애뮬로 확인하면 똑같습니다.    ex) 메인xml에 텍스트 글씨를 빨간색으로바꾸어도 애뮬은 여전히 검정색으로 나옴 

화면 구성을 다시하고 싶은데 해결을 못하고 있습니다 ㅜㅜㅜ

**Comment by rhsekdl12** [comment]
https://github.com/rhsekdl12/BabsangAppDoc/blob/master/image.png

혹시나해서 작업중인 안드로이드 메인 xml화면부분 캡처해서 올립니다. 

감사합니다.

**Comment by waterux** [comment]
답이 늦어서 미안해요.

말해준 문제에 대해서 굉장히 다양한 원인이 있을 수 있는데 현재 올려준 이미지 파일로는 정확한 원인을 파악하기 힘드네요. 

현재 깃에 올려진 소스를 최신으로 푸시하고 다시 알려주면 소스 다운받아서 확인해볼께요.

**Comment by rhsekdl12** [comment]
답변 감사합니다!!
교수님 말씀대로 지금까지 한 소스 푸쉬완료했습니다. 

감사합니다.

**Comment by yuhanappdev** [comment]
![image](https://user-images.githubusercontent.com/63232395/84589604-c00c0100-ae6a-11ea-83f4-9a5e4caf0421.png)

![image](https://user-images.githubusercontent.com/63232395/84589608-c4d0b500-ae6a-11ea-9f88-8c6d9b68213a.png)

스크린샷을 정확히 찍었으면 두번 질문 안해도 되겠네요. 
지금 activity_main.xml 이 두개 등록되어 있고 v21 이라고 되어 있는 부분이 적용되어 있네요.

원상태로 돌리는게 힘들다면 v21이라고 표시되어 있는 activity_main.xml을 편집해요.

**Comment by rhsekdl12** [comment]
한번 더 집중있게 봤어야하는데, 번거롭게해드려서 죄송합니다.
끝까지 열심히해서 되는만큼 완성해보겠습니다. 

감사합니다.
